replicaCount: 1

image:
  repository: hashicorp/vault
  pullPolicy: IfNotPresent
  tag: "1.19.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}
podSecurityContext:
  fsGroup: 1000 
  runAsUser: 100
  runAsGroup: 1000

securityContext:
  capabilities:
    add: ["IPC_LOCK"]

# Service for internal cluster communication (e.g., for Vault agent, app access)
service:
  type: ClusterIP
  port: 8200

uiService:
  enabled: true
  type: LoadBalancer 
  port: 8200

persistence:
  enabled: true
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  size: 2Gi 

vaultConfig: |
  ui = true

  listener "tcp" {
    address          = "0.0.0.0:8200"
    cluster_address  = "0.0.0.0:8201"
    tls_disable      = "true"
  }

raft:
  path: "/vault/file"

nodeSelector: {}
tolerations: []
affinity: {}
