{{- $chartName := include "papikos-app.name" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "papikos-app.fullname" . }}
  labels:
    {{- include "papikos-app.labels" . | nindent 4 }}
  annotations:
    # Add any global annotations you need here
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  {{- if .Values.frontend.ingress.enabled }}
  - host: {{ .Values.frontend.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.service.name | default (printf "%s-frontend" (include "papikos-app.fullname" .)) }} # Defaulting service name convention
            port:
              number: {{ .Values.frontend.service.port }}
  {{- end }}

  {{- if .Values.auth.ingress.enabled }}
  - host: {{ .Values.auth.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.auth.service.name | default (printf "%s-auth" (include "papikos-app.fullname" .)) }} # Defaulting service name convention
            port:
              number: {{ .Values.auth.service.port }}
  {{- end }}
  
  {{- if .Values.kos.ingress.enabled }}
  - host: {{ .Values.kos.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.kos.service.name | default (printf "%s-kos" (include "papikos-app.fullname" .)) }} # Defaulting service name convention
            port:
              number: {{ .Values.kos.service.port }}
  {{- end }}

