{{- $top := . -}}
{{- $authValues := .Values.auth -}}
{{- $globalValues := .Values.global -}}
{{- range $color := list "blue" "green" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "papikos-app.fullname" $top }}-auth-{{ $color }}
  labels:
    {{- include "papikos-app.labels" $top | nindent 4 }}
    app.kubernetes.io/component: auth
    version: {{ $color }}
spec:
  replicas: {{ $authValues.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "papikos-app.selectorLabels" $top | nindent 6 }}
      app.kubernetes.io/component: auth
      version: {{ $color }} 
  template:
    metadata:
      labels:
        {{- include "papikos-app.selectorLabels" $top | nindent 8 }}
        app.kubernetes.io/component: auth # Keep this to identify as auth pods
        version: {{ $color }}
    spec:
      {{- with $top.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "papikos-app.serviceAccountName" $top }}
      securityContext:
        {{- toYaml $top.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: auth
          securityContext:
            {{- toYaml $authValues.securityContext | default $top.Values.securityContext | nindent 12 }}
          image: "{{ $authValues.image.repository }}:{{ $authValues.image.tag | default $top.Chart.AppVersion }}"
          imagePullPolicy: {{ $authValues.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ $authValues.service.port }}
              protocol: TCP
          resources:
            {{- toYaml $authValues.resources | default $top.Values.resources | nindent 12 }}
          {{- if $authValues.config.enabled }}
          {{- if $authValues.config.mountAllKeysFromSecret }}
          envFrom:
            - secretRef:
                name: {{ $authValues.config.mountAllKeysFromSecret }}
            - secretRef:
                name: {{ $authValues.rabbitmq.mountAllKeysFromSecret }}
          {{- else if $authValues.config.secretName }}
          envFrom:
            - secretRef:
                name: {{ $authValues.rabbitmq.mountAllKeysFromSecret }}
          env:
            {{- range $authValues.config.envMappings }}
            - name: {{ .envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ $authValues.config.secretName }}
                  key: {{ .key }}
            {{- end }}
          {{- end }}
          {{- end }}
      {{- with $top.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $top.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $top.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}

