# values.yaml
global:
  activeColor: blue
  # Global image settings
  imageRegistry: asia-southeast1-docker.pkg.dev/belajar-kube-457207/papikos-repository
  # Default image pull policy
  imagePullPolicy: Always
ingress:
  annotations: {}
  # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
serviceAccount:
  create: false
  name: "default"
frontend:
  image:
    repository: asia-southeast1-docker.pkg.dev/belajar-kube-457207/papikos-repository/papikos-fe
    tag: v0.0.1
    imagePullPolicy: Always
  service:
    name: frontend
    port: 3000
  ingress:
    enabled: true
    host: papikos.shop
    # tls: # Optional TLS configuration for frontend
    # - hosts:
    #   - papikos.shop
    #   secretName: papikos-shop-tls
auth:
  image:
    repository: asia-southeast1-docker.pkg.dev/belajar-kube-457207/papikos-repository/papikos-auth
    tag: v0.0.4 # This will be automatically updated by CI/CD
    imagePullPolicy: Always
  service:
    name: auth
    port: 8080
  ingress:
    enabled: true
    host: auth.papikos.shop
    # tls: # Optional TLS configuration for auth
    # - hosts:
    #   - auth.papikos.shop
    #   secretName: auth-papikos-shop-tls
  # Database configuration from Kubernetes Secret
  config:
    enabled: true
    secretName: "auth-configuration"
    envMappings:
      - key: DB_HOST
        envName: DB_HOST
      - key: DB_NAME
        envName: DB_NAME
      - key: DB_PORT
        envName: DB_PORT
      - key: DB_USER
        envName: DB_USER
      - key: DB_PASSWORD
        envName: DB_PASSWORD
      - key: JWT_SECRET
        envName: JWT_SECRET
      - key: ADMIN_EMAIL
        envName: ADMIN_EMAIL
      - key: ADMIN_PASSWORD
        envName: ADMIN_PASSWORD
kos:
  image:
    repository: asia-southeast1-docker.pkg.dev/belajar-kube-457207/papikos-repository/papikos-kos
    tag: v0.0.1 # This will be automatically updated by CI/CD
    imagePullPolicy: Always
  service:
    name: kos
    port: 8080
  ingress:
    enabled: true
    host: kos.papikos.shop
    # tls: # Optional TLS configuration for kos
    # - hosts:
    #   - kos.papikos.shop
    #   secretName: kos-papikos-shop-tls
  # Database configuration from Kubernetes Secret
  config:
    enabled: true
    secretName: "kos-configuration"
    envMappings:
      - key: DB_HOST
        envName: DB_HOST
      - key: DB_NAME
        envName: DB_NAME
      - key: DB_PORT
        envName: DB_PORT
      - key: DB_USER
        envName: DB_USER
      - key: DB_PASSWORD
        envName: DB_PASSWORD
      - key: AUTH_SERVER_URL
        envName: AUTH_SERVER_URL
    # mountAllKeysFromSecret: "kos-database-credentials"
version:
  auth: latest # Current deployed version
  frontend: latest # Current deployed version
  kos: latest # Current deployed version
  lastUpdated: "" # Timestamp of last update
  deployedBy: "" # Who triggered the deployment
