apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault-secrets.fullname" . }}-config
  labels:
    {{- include "vault-secrets.labels" . | nindent 4 }}
data:
  vault.hcl: |
    {{- include "vault-secrets.vaultConfigHCL" . | nindent 4 }}
