# Headless service for StatefulSet DNS resolution (important for Raft)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-secrets.fullname" . }}-headless
  labels:
    {{- include "vault-secrets.labels" . | nindent 4 }}
spec:
  clusterIP: None # Headless
  publishNotReadyAddresses: true # Important for Raft bootstrapping
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: cluster
      port: 8201
      targetPort: cluster
      protocol: TCP
  selector:
    {{- include "vault-secrets.selectorLabels" . | nindent 4 }}
---
# Regular ClusterIP service for internal access to Vault API
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-secrets.fullname" . }}
  labels:
    {{- include "vault-secrets.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vault-secrets.selectorLabels" . | nindent 4 }}
