apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.service.name | default (printf "%s-auth" (include "papikos-app.fullname" .)) }}
  labels:
    {{- include "papikos-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: {{ .Values.auth.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: http 
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "papikos-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth
    version: {{ .Values.global.activeColor }} 

